bldr:
    profiles:
        default:
            description: 'Development Profile'
            tasks:
                - test
        test:
            description: "Test Profile"
            tasks:
                - testDev        